apiVersion: v1
kind: Service
metadata:
  name: json-exporter-service
  namespace: monitoring
spec:
  selector:
    app: json-exporter
  ports:
    - protocol: TCP
      port: 7979
      targetPort: 7979
  type: ClusterIP
