- name: Update apt cache
  apt:
    update_cache: yes

- name: Add deadsnakes PPA for Python versions
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install essential packages
  apt:
    name:
      - curl
      - git
      - python3.10
      - python3.10-venv
      - python3.10-dev
      - python3-pip
    state: present