apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: product-store
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort

