apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-store-backend-v1
  labels:
    app: product-store
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-store
      version: v1
  template:
    metadata:
      labels:
        app: product-store
        version: v1
    spec:
      containers:
      - name: backend
        image: bradesteve/product-store-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DATABASE_URL
          value: "mysql+pymysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql-service:3306/product_store"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-store-backend-v2
  labels:
    app: product-store
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-store
      version: v2
  template:
    metadata:
      labels:
        app: product-store
        version: v2
    spec:
      containers:
      - name: backend
        image: bradesteve/product-store-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DATABASE_URL
          value: "mysql+pymysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql-service:3306/product_store"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
