version: '3.9'

services:
  # Backend service (Flask)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_store_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  # Database service (MySQL)
  db:
    image: mysql:8.0
    container_name: product_store_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:  # Persist the MySQL database data
