apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: YnJhZA==  # Base64 encoded value of 'brad'
  MYSQL_PASSWORD: YnJhZF9zdGV2ZQ==  # Base64 encoded value of 'brad_steve'
