- name: Load database variables
  include_vars: vars.yml

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Create MySQL database
  command: >
    mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"

- name: Create MySQL user
  command: >
    mysql -u root -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';"

- name: Grant privileges to user
  command: >
    mysql -u root -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"