- name: Install backend dependencies
  ansible.builtin.pip:
    requirements: /vagrant/app/requirements.txt
  # shell: |
  #   pip3 install -r /vagrant/app/requirements.txt
  # args:
  #   executable: /bin/bash


- name: Set PYTHONPATH environment variable
  shell: |
    echo 'export PYTHONPATH="/vagrant/app"' >> ~/.bashrc
    export PYTHONPATH="/vagrant/app"
  args:
    executable: /bin/bash

- name: Run Flask app
  shell: |
    cd /vagrant
    nohup python3 run.py --host=0.0.0.0 --port=5000 &
  args:
    executable: /bin/bash
