# - name: Install Python dependencies for backend
#   pip:
#     requirements: /vagrant/requirements.txt
#     virtualenv: /vagrant/venv

# - name: Start Flask app
#   shell: |
#     source /vagrant/venv/bin/activate
#     FLASK_ENV=development python3 /vagrant/run.py
#   args:
#     chdir: /vagrant
#   async: 1
#   poll: 0


# - name: Install Python3 and pip
#   apt:
#     name:
#       - python3
#       - python3-pip
#     state: present

# - name: Install backend dependencies
#   pip:
#     requirements: /vagrant/requirements.txt

# - name: Run Flask app
#   shell: |
#     nohup python3 /vagrant/run.py --host=0.0.0.0 &
#   args:
#     executable: /bin/bash


- name: Install backend dependencies
  ansible.builtin.pip:
    requirements: /vagrant/app/requirements.txt
  # shell: |
  #   pip3 install -r /vagrant/app/requirements.txt
  # args:
  #   executable: /bin/bash


- name: Set PYTHONPATH environment variable
  shell: |
    echo 'export PYTHONPATH="/vagrant/app"' >> ~/.bashrc
    export PYTHONPATH="/vagrant/app"
  args:
    executable: /bin/bash

- name: Run Flask app
  shell: |
    cd /vagrant
    nohup python3 run.py --host=0.0.0.0 --port=5000 &
  args:
    executable: /bin/bash
