# - name: Install Node.js dependencies for frontend
#   npm:
#     path: /vagrant/product-api-frontend
#     state: present

# - name: Start React app
#   shell: npm start
#   args:
#     chdir: /vagrant/product-api-frontend
#   async: 1
#   poll: 0


# - name: Install Node.js and npm
#   apt:
#     name:
#       - nodejs
#       - npm
#     state: present

# - name: Install NVM
#   shell: |
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
#     export NVM_DIR="$HOME/.nvm"
#     . "$NVM_DIR/nvm.sh"
#     nvm install 20
#     nvm use 20
#   args:
#     executable: /bin/bash

# - name: Move React app out of synced folder
#   command: cp -r /vagrant/product-api-frontend ~/product-api-frontend

# - name: Install React dependencies
#   shell: |
#     cd ~/product-api-frontend
#     npm install
#   args:
#     executable: /bin/bash

# - name: Start React app
#   shell: |
#     cd ~/product-api-frontend
#     BROWSER=none nohup npm start &
#   args:
#     executable: /bin/bash


- name: Install NVM
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    . "$NVM_DIR/nvm.sh"
    nvm install 20
    nvm use 20
  args:
    executable: /bin/bash

- name: Persist NVM in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

- name: Copy React app to home directory
  command: rsync -a /vagrant/product-api-frontend ~/product-api-frontend

- name: Install React dependencies
  shell: |
    cd ~/product-api-frontend
    npm install
  args:
    executable: /bin/bash

- name: Start React app
  shell: |
    cd ~/product-api-frontend
    BROWSER=none nohup npm start --port=3000 &
  args:
    executable: /bin/bash
